# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DisenoDeInterfaces.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(541, 818)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 80, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.cb_COM = QtWidgets.QComboBox(self.centralwidget)
        self.cb_COM.setGeometry(QtCore.QRect(170, 90, 141, 41))
        self.cb_COM.setObjectName("cb_COM")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(330, 90, 151, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 210, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_actualizar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_actualizar.setGeometry(QtCore.QRect(190, 150, 93, 28))
        self.btn_actualizar.setObjectName("btn_actualizar")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 150, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.txt_info = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_info.setGeometry(QtCore.QRect(80, 290, 371, 41))
        self.txt_info.setObjectName("txt_info")
        self.btn_enviar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_enviar.setGeometry(QtCore.QRect(220, 350, 93, 28))
        self.btn_enviar.setObjectName("btn_enviar")
        self.txt_monitor = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_monitor.setGeometry(QtCore.QRect(80, 400, 361, 291))
        self.txt_monitor.setReadOnly(True)
        self.txt_monitor.setObjectName("txt_monitor")
        self.btn_abrir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_abrir.setGeometry(QtCore.QRect(70, 710, 51, 23))
        self.btn_abrir.setObjectName("btn_abrir")
        self.btn_cerrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cerrar.setGeometry(QtCore.QRect(130, 710, 51, 23))
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.btn_auto = QtWidgets.QPushButton(self.centralwidget)
        self.btn_auto.setGeometry(QtCore.QRect(190, 710, 51, 23))
        self.btn_auto.setObjectName("btn_auto")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 541, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "COM:"))
        self.label_2.setText(_translate("MainWindow", "Desconectado"))
        self.btn_actualizar.setText(_translate("MainWindow", "Actualizar"))
        self.pushButton_2.setText(_translate("MainWindow", "Cancelar"))
        self.btn_enviar.setText(_translate("MainWindow", "Enviar"))
        self.btn_abrir.setText(_translate("MainWindow", "A"))
        self.btn_cerrar.setText(_translate("MainWindow", "C"))
        self.btn_auto.setText(_translate("MainWindow", "R"))
